# Generated by Django 3.2.7 on 2022-02-01 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tbl_bookingid',
        ),
        migrations.CreateModel(
            name='Book_with_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bwo_booking', to='restaurant.booking')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bwo_order', to='restaurant.order')),
            ],
        ),
    ]
