# Generated by Django 3.2.7 on 2022-02-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20220201_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(blank=True, choices=[('takeaway', 'Takeaway'), ('dine-in', 'dine-in')], default='takeaway', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('canceled', 'Canceled'), ('done', 'Done')], default='confirmed', max_length=10),
        ),
    ]
