# Generated by Django 3.2.7 on 2022-02-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20220202_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(blank=True, choices=[('takeaway', 'Takeaway'), ('dine-in', 'dine-in')], default='takeaway', max_length=10),
        ),
    ]
