# Generated by Django 3.2.7 on 2022-02-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_booking_booking_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='order_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(blank=True, choices=[('takeaway', 'Takeaway'), ('dine-in', 'dine-in'), ('none', 'None')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(blank=True, choices=[('takeaway', 'Takeaway'), ('dine-in', 'dine-in'), ('none', 'None')], default='takeaway', max_length=10),
        ),
    ]
