# Generated by Django 3.2.7 on 2022-02-09 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_auto_20220209_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='order_id',
            new_name='razorpay_order_id',
        ),
    ]
