# Generated by Django 3.2.7 on 2022-02-10 07:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_rename_order_id_booking_razorpay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='book_til',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
