# Generated by Django 3.2.7 on 2022-02-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_booking_book_til'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_details',
            name='booking_type',
            field=models.CharField(blank=True, choices=[('takeaway', 'Takeaway'), ('dine-in', 'dine-in'), ('none', 'None')], default='none', max_length=10),
        ),
    ]
