# Generated by Django 3.2.7 on 2022-02-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_booking_details_booking_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='b_type',
            field=models.CharField(blank=True, choices=[('takeaway', 'Takeaway'), ('dine-in', 'dine-in'), ('none', 'None')], default='none', max_length=10),
        ),
    ]
