# Generated by Django 3.2.7 on 2022-02-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_booking_b_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='max',
            field=models.CharField(blank=True, default=4, max_length=10, null=True),
        ),
    ]
