# Generated by Django 4.0.2 on 2022-02-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_table_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='confirm',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
