# Generated by Django 3.2.7 on 2022-03-11 16:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_booking_confirm'),
    ]

    operations = [
        migrations.CreateModel(
            name='tables_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('time', models.TimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('book_til', models.TimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('tbl_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_table', to='restaurant.table')),
            ],
        ),
    ]
